name: Trivy scan
description: |
  Scan repository and / or image to detect CVEs.
  Allows updating Github's security tab and send alert on slack channels.
inputs:
  CONTAINER_REGISTRY_USER:
    description: Docker registry user.
    type: string
    required: true
  CONTAINER_REGISTRY_TOKEN:
    description: Docker registry token.
    type: string
    required: true
  SLACK_APP_TOKEN:
    description: |
      Token used to send messages on slack.
      Required if 'channels' is set.
    type: string
    required: false
  ref:
    description: |
      Branch or tag the scan is associated to.
      Required if using 'fs' scan-type and / or uploading sarif.
    type: string
    required: false
  scan-type: 
    description: |
      Type of analysis: 'image' for docker images, 'fs' for files.
      Defaults to 'fs'.
    required: false
    type: choice
    options: 
      - fs
      - image
    default: fs
  vuln-type: 
    description: |
      Scan target: 'os' for base docker image, 'library' for dependencies, 'os,library' for both.
      Defaults to 'library'.
    required: false
    type: choice
    options: 
      - os
      - library
      - os,library
    default: library
  scan-target:
    description: |
      Folder or docker image to scan.
      Defaults to respository folder.
    type: string
    required: false
    default: '.'
  upload-sarif:
    description: |
      Update Github's security tab with results.
      Defaults to true.
    required: false
    type: boolean
    default: true
  slack-channels:
    description: Comma separated slack channels to notify scan results.
    type: string
    required: false

runs:
  using: composite
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ ( '${{ inputs.scan-type }}' == 'fs' || '${{ inputs.upload-sarif}}' == 'true' ) && '${{ inputs.ref }}' == '' ]]; then
          echo "::error::Input 'ref' must be filled if input 'scan-type' is set to 'fs' or uploading sarif"
          exit 1
        fi

        if [[ '${{ inputs.slack-channels }}' != '' && '${{ inputs.SLACK_APP_TOKEN }}' == '' ]]; then
          echo "::error::Input 'SLACK_APP_TOKEN' is mandatory if input 'slack-channels' is provided.'"
          exit 1
        fi

    - name: Checkout repository
      if: ${{ inputs.ref != '' }}
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref }}

    - name: Login to Quay.io
      if: ${{ inputs.scan-type == 'image' }}
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ inputs.CONTAINER_REGISTRY_USER }}
        password: ${{ inputs.CONTAINER_REGISTRY_TOKEN }}

    - name: Pull docker image
      if: ${{ inputs.scan-type == 'image' }}
      shell: bash
      run: docker pull ${{ inputs.scan-target }}

    - name: Trivy scan
      id: trivy-scan
      shell: bash
      run: |
        # Enable aliases
        shopt -s expand_aliases
        alias trivy="docker run -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/results aquasec/trivy"

        # Scan docker image
        trivy ${{ inputs.scan-type }} --exit-code 42 --scanners vuln --vuln-type ${{ inputs.vuln-type }} --format json --output /results/trivy.json ${{ inputs.scan-target }} || output_code=$?

        if [[ $output_code != '' && $output_code != 42  ]]; then
          exit $output_code
        fi

        trivy convert --format sarif --output /results/trivy.sarif /results/trivy.json

        if [[ $output_code == 42 ]]; then
          trivy convert --format table --output /results/trivy.txt /results/trivy.json
          trivy_text_template='{{- $critical := 0 }}{{- $high := 0 }}{{- $medium := 0 }}{{- $low := 0 }}{{- range . }}{{- range .Vulnerabilities }}{{- if  eq .Severity "CRITICAL" }}{{- $critical = add $critical 1 }}{{- end }}{{- if  eq .Severity "HIGH" }}{{- $high = add $high 1 }}{{- end }}{{- if  eq .Severity "MEDIUM" }}{{- $medium = add $medium 1 }}{{- end }}{{- if  eq .Severity "LOW" }}{{- $low = add $low 1 }}{{- end }}{{- end }}{{- end }}{{- if gt $critical 0 }}🔥 Critical: {{ $critical }}{{- end }}{{- if gt $high 0 }} 🔴 High: {{ $high }}{{- end }}{{- if gt $medium 0 }} 🟠 Medium: {{ $medium }}{{- end }}{{- if gt $low 0 }} 🟡 Low: {{ $low }}{{- end }}'
          echo "TRIVY_IMAGE_TXT=$(trivy convert --format template --template "$trivy_text_template" /results/trivy.json)" >> $GITHUB_OUTPUT
        fi

    - name: Set ref
      id: set-ref-and-sha
      shell: bash
      run: |
        echo "ref=refs/$(git describe --all)" >> $GITHUB_OUTPUT
        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Upload sarif
      if: ${{ inputs.upload-sarif == 'true' }}
      uses: github/codeql-action/upload-sarif@v3
      with:
        ref: ${{ steps.set-ref-and-sha.outputs.ref }}
        sha: ${{ steps.set-ref-and-sha.outputs.sha }}
        sarif_file: 'trivy.sarif'
        category: ${{ inputs.vuln-type }}

    - name: Slack Notification
      if: ${{ inputs.slack-channels != '' && hashFiles('trivy.txt') != '' }}
      shell: bash
      run: |
        if [[ '${{ inputs.upload-sarif }}' == 'true' ]]; then
          tab_message="Github's security tab has been updated: ${{ github.server_url }}/${{ github.repository }}/security/code-scanning?query=is:open+ref:${{ steps.set-ref-and-sha.outputs.ref }}"
        fi
        if [[ '${{ inputs.ref }}' != '' ]]; then
          ref_message="for ref '${{ inputs.ref }}'"
        fi
        curl -F file=@trivy.txt \
             -F channels=${{ inputs.slack-channels }} \
             -F initial_comment="Trivy scan : ${{ inputs.scan-type }}
        Found the following CVEs on repository '${{ github.repository }}' $ref_message
        ${{ steps.trivy-scan.outputs.TRIVY_IMAGE_TXT }}
        $tab_message" \
             -H 'Authorization: Bearer ${{ inputs.SLACK_APP_TOKEN }}' \
             https://slack.com/api/files.upload