name: Daily specific scan

on:
  workflow_dispatch: # Allow to manually trigger the pipeline
  schedule:
    - cron: "0 7 * * *" # Every day at 7am GMT

jobs:
  daily-image-scan:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        image:
          - { ref: "master", name: "quay.io/evooq/montblanc:dev" }
          - { ref: "202308", name: "quay.io/evooq/montblanc-branch:202308-latest" }
          - { ref: "202309", name: "quay.io/evooq/montblanc-branch:202309-latest" }
          - { ref: "202310", name: "quay.io/evooq/montblanc-branch:202310-latest" }
          - { ref: "202312", name: "quay.io/evooq/montblanc-branch:202312-latest" }

    steps:
      - name: Scan image
        uses: evooq/image-scanner@v1
        with:
          ref: ${{ matrix.image.ref }}
          scan-type: image
          vuln-type: os,library
          scan-target: ${{ matrix.image.name }}
          slack-channels: ${{ secrets.SLACK_CHANNEL_ID }}
          CONTAINER_REGISTRY_USER: ${{ secrets.CONTAINER_REGISTRY_USER }}
          CONTAINER_REGISTRY_TOKEN: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
